Homework 1 - complete
DimitriIlnitski/courses-app pull request #1
Opened 2023-03-22 15:18 UTC by DimitriIlnitski

In main branch located just project created by create-react-app.

2023-03-22 16:28 UTC, KitTheProgrammer requested changes
While checking you app I found:
1. There is no "cancel" button when creating new course
2. When clicking on "create new author" with empty string no alert or error appears

2023-03-22 16:28 UTC, KitTheProgrammer commented on .eslintrc.json
Feels like something wrong with formatting here

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +		let value = e.target.value;
You can use parameters destruction here: `const func = ({ target: { value } }) => {}`

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +				})}
Use a separate render function for this portion

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/Courses/Courses.jsx
> +				})}
like this: 
`const renderCourses = () => {<highlighted block>}`

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +		setTitle(value);
param destruction

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +	};
here too

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +									})
These parts look very similar. Try to find a way to combine them using a render function

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/AddAuthor/AddAuthor.jsx
> +	};
destruction

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/common/Input/Input.jsx
You don't need separate classes for input and the label. 
You can provide one class to your label (which you can name `className` to follow the convention) and then address your input via css selector `.label-class > input {} ` or `.label-class input {} `

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/AddAuthor/AddAuthor.jsx
> +					getInputData={newAuthorName}
this part will need some refactoring after you fix your classNames approach

2023-03-22 16:28 UTC, KitTheProgrammer commented on src/common/Input/Input.jsx
Don't forget to refactor parts of the code that can be affected by the change

2023-03-22 18:31 UTC, DimitriIlnitski commented on src/common/Input/Input.jsx
I have used BEM methodology for css. As I know it forsee use of classes only, with minor use of attribute selectors, pseudo-classes, or pseudo-elements. Thus, I would stay with initial code. But If you insist I can change code as your requirements.

2023-03-22 18:32 UTC, DimitriIlnitski commented on src/components/CreateCourse/components/AddAuthor/AddAuthor.jsx
> +					getInputData={newAuthorName}
Linked to above comment.

2023-03-22 18:32 UTC, DimitriIlnitski commented on src/components/CreateCourse/components/AddAuthor/AddAuthor.jsx
> +	};
Done.

2023-03-22 18:32 UTC, DimitriIlnitski commented on src/components/CreateCourse/CreateCourse.jsx
> +									})
Done

2023-03-22 18:32 UTC, DimitriIlnitski commented on src/components/CreateCourse/CreateCourse.jsx
> +	};
Done,

2023-03-22 18:33 UTC, DimitriIlnitski commented on src/components/CreateCourse/CreateCourse.jsx
> +		setTitle(value);
Done

2023-03-22 18:33 UTC, DimitriIlnitski commented on src/components/Courses/Courses.jsx
> +				})}
Done

2023-03-22 18:33 UTC, DimitriIlnitski commented on src/components/Courses/Courses.jsx
> +		let value = e.target.value;
Done

2023-03-22 18:41 UTC, DimitriIlnitski commented on .eslintrc.json
1. Our layout do not forsee button "Cancel". If its necessaey I can add it. Pls describe what functionalityю
2. CreateCourse.jsx - function createCourse contain code, which send alert in case if title or description or duration or course authors are empty. Should I add or change smth?

2023-03-22 20:40 UTC, KitTheProgrammer requested changes

2023-03-22 20:40 UTC, KitTheProgrammer commented on src/components/CreateCourse/CreateCourse.jsx
> +	};
Here you did not exactly what I meant.

If you look at your initial code you will see that the only difference between the two pars is the array from which you are gathering data `availableAuthors`; `courseAuthors` and button text `buttonInfo`.

So those are the only thing you have to change.

```suggestion
	const renderAuthorList = (authors, buttonInfo ) => (
			<ul className='create-course__list'>
				{authors.length === 0 ? (
					<li className='create-course__list--empty'>Author list is empty</li>
				) : (
					authors.map((author) => (
						<AuthorTile
							key={author.id}
							author={author}
							buttonInfo={buttonInfo}
							courseAuthors={courseAuthors}
							setCourseAuthors={setCourseAuthors}
							availableAuthors={availableAuthors}
							setAvailableAuthors={setAvailableAuthors}
						/>
					))
				)}
			</ul>
		);
```

and lower in the code you will have something like this:

`{renderAuthorList(availableAuthors, ADD_AUTHOR)}`
and
`{renderAuthorList(courseAuthors, DELETE_AUTHOR)}`

2023-03-22 20:43 UTC, KitTheProgrammer approved these changes
Please, don't forget to fix above comment

20

2023-03-23 07:59 UTC, DimitriIlnitski commented on src/components/CreateCourse/CreateCourse.jsx
> +	};
I have made necessary correction. Thanks a lot for your support!

2023-03-23 08:00 UTC, merged